# Generated by Django 4.2.24 on 2025-09-27 17:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['date', 'start'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.RemoveField(
            model_name='events',
            name='number_attending',
        ),
        migrations.AddField(
            model_name='events',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='events',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='max_attendees',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='events',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all', 'All Levels')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='events',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_sports',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[('soccer', 'Soccer'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball'), ('baseball', 'Baseball'), ('football', 'Football'), ('softball', 'Softball'), ('golf', 'Golf'), ('ultimate_frisbee', 'Ultimate Frisbee'), ('cycling', 'Cycling'), ('running', 'Running'), ('swimming', 'Swimming'), ('badminton', 'Badminton'), ('table_tennis', 'Table Tennis'), ('cricket', 'Cricket'), ('rugby', 'Rugby'), ('hockey', 'Hockey'), ('chess', 'Chess'), ('other', 'Other')], max_length=64),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='events',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_hosted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sports.events')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
