# Generated by Django 5.2.6 on 2025-09-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_alter_events_options_remove_events_number_attending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_sports',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
